# Generated by Django 4.2.17 on 2025-01-24 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=30)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(error_messages={'invalid': 'Por favor, insira um e-mail válido.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Endereço de e-mail da instituição')),
            ],
        ),
    ]
