# Generated by Django 4.2.17 on 2025-01-24 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=30, verbose_name='Matricula')),
                ('email', models.EmailField(error_messages={'invalid': 'Por favor, insira um e-mail válido.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail Institucional')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
